### ISSUE TITLE
Crucible variants are unsmeltable

### ISSUE THREAD

**Issue by starrypop** [starrypop/Natural-Clay#1]
Crucible variants are unable to be smelted, they throw an error.

`19.4.2024 09:59:02 [Error] Exception: Can't create itemstack without block!
   at Vintagestory.API.Common.ItemStack..ctor(Block block, Int32 stacksize) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 242
   at Vintagestory.GameContent.BlockSmeltingContainer.DoSmelt(IWorldAccessor world, ISlotProvider cookingSlotsProvider, ItemSlot inputSlot, ItemSlot outputSlot) in VSSurvivalMod\Block\BlockSmeltingContainer.cs:line 93
   at Vintagestory.GameContent.BlockEntityFirepit.smeltItems_Patch2(BlockEntityFirepit this)
   at Vintagestory.GameContent.BlockEntityFirepit.OnBurnTick_Patch2(BlockEntityFirepit this, Single dt)
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27`

**Comment by Zergmazter** [comment]
I'm having the same issue.
